category_1 = {
    'Одежда, обувь': 'Clothing, shoes',
    'Одежда': 'Clothing',
    'Товары с быстрой доставкой': 'Fast delivery products',
    'Товары для дома': 'Home goods',
    'Спорт и отдых': 'Sports and leisure',
    'Электроника': 'Electronics',
    'Товары ReCommerce': 'ReCommerce products'
}

category_2 = {
    'Мужская обувь': 'Men\'s shoes',
    'Женская обувь': 'Women\'s shoes',
    'Мужская одежда': 'Men\'s clothing',
    'Женская одежда': 'Women\'s clothing',
    'Детская одежда': 'Children\'s clothing',
    'Детские аксессуары': 'Children\'s accessories',
    'Женские аксессуары': 'Women\'s accessories',
    'Мужские аксессуары': 'Men\'s accessories',
    'Уход за волосами': 'Hair care',
    'Текстиль для дома': 'Home textiles',
    'Игрушки': 'Toys',
    'Зимние виды спорта': 'Winter sports',
    'Походы и активный отдых': 'Hiking and outdoor activities',
    'Колесный спорт': 'Wheel sports',
    'Постельное белье': 'Bedding',
    'nan': 'None',  
    'Охота и рыбалка': 'Hunting and fishing',
    'Фитнес и спортзал': 'Fitness and gym',
    'Командные виды спорта': 'Team sports',
    'Умные часы и браслеты': 'Smartwatches and bracelets',
    'Бег и ходьба': 'Running and walking',
    'Теннис и бадминтон': 'Tennis and badminton',
    'Водные виды спорта': 'Water sports',
    'Запчасти': 'Spare parts',
    'Йога': 'Yoga'
}

category_3 = {
    'Кроссовки': 'Sneakers',
    'Верхняя одежда': 'Outerwear',
    'Кеды': 'Canvas shoes',
    'Кроссовки, кеды, бутсы': 'Sneakers, canvas shoes, cleats',
    'Толстовки и свитшоты': 'Hoodies and sweatshirts',
    'Слипоны': 'Slip-ons',
    'Домашняя одежда': 'Homewear',
    'Футболки': 'T-shirts',
    'Одежда для спорта': 'Sportswear',
    'Джемперы, свитеры и кардиганы': 'Jumpers, sweaters, and cardigans',
    'Брюки': 'Trousers',
    'Блузы и рубашки': 'Blouses and shirts',
    'Платья и сарафаны': 'Dresses and sundresses',
    'Худи, толстовки, свитшоты': 'Hoodies, sweatshirts, and sweaters',
    'Джинсы': 'Jeans',
    'Рубашки': 'Shirts',
    'Пиджаки, жакеты и жилеты': 'Blazers, jackets, and vests',
    'Пиджаки, жилеты и костюмы': 'Blazers, vests, and suits',
    'Шорты': 'Shorts',
    'Футболки и поло': 'T-shirts and polos',
    'Юбки': 'Skirts',
    'Термобелье': 'Thermal underwear',
    'Лонгсливы': 'Long sleeves',
    'Леггинсы': 'Leggings',
    'Топы и майки': 'Tops and tank tops',
    'Носки и колготки': 'Socks and tights',
    'Нижнее белье': 'Underwear',
    'Комбинезоны': 'Overalls',
    'Носки': 'Socks',
    'Для девочек': 'For girls',
    'Для мальчиков': 'For boys',
    'nan': 'None',
    'Для новорожденных': 'For newborns',
    'Пляжная одежда': 'Beachwear',
    'Боди': 'Bodysuits',
    'Майки': 'Tank tops',
    'Сапоги и полусапожки': 'Boots and ankle boots',
    'Головные уборы': 'Headwear',
    'Костюмы и комплекты': 'Suits and sets',
    'Аксессуары для девочек': 'Accessories for girls',
    'Аксессуары для мальчиков': 'Accessories for boys',
    'Средства для укладки волос': 'Hair styling products',
    'Полотенца': 'Towels',
    'Игрушки для малышей': 'Toys for toddlers',
    'Аксессуары для новорожденных': 'Newborn accessories',
    'Аксессуары для волос': 'Hair accessories',
    'Ремни': 'Belts',
    'Треккинг': 'Trekking',
    'Одежда': 'Clothing',
    'Лыжный спорт': 'Skiing',
    'Рюкзаки': 'Backpacks',
    'Карнавальные костюмы': 'Costumes',
    'Парусный спорт': 'Sailing',
    'Футбол': 'Football',
    'Велоспорт': 'Cycling',
    'Плавание': 'Swimming',
    'Сандалии': 'Sandals',
    'Большой теннис': 'Tennis',
    'Кошельки': 'Wallets',
    'Обувь для мальчиков': 'Boys\' shoes',
    'Бриджи и капри': 'Capri pants and shorts',
    'Серфинг и вейкбординг': 'Surfing and wakeboarding',
    'Умные часы': 'Smartwatches'
}

category_4 = {
    'Толстовки': 'Hoodies',
    'Куртки': 'Jackets',
    'Пуховики': 'Down jackets',
    'Халаты': 'Robes',
    'Жилеты': 'Vests',
    'Костюмы': 'Suits',
    'Пальто': 'Coats',
    'Брюки': 'Trousers',
    'Парки': 'Parkas',
    'Леггинсы': 'Leggings',
    'Плащи и тренчи': 'Raincoats and trench coats',
    'Джемперы': 'Jumpers',
    'Блузы': 'Blouses',
    'Рубашки': 'Shirts',
    'Платья': 'Dresses',
    'Свитшоты': 'Sweatshirts',
    'Свитеры': 'Sweaters',
    'Пиджаки': 'Blazers',
    'Жакеты': 'Jackets',
    'Сарафаны': 'Sundresses',
    'Худи': 'Hoodies',
    'Кардиганы': 'Cardigans',
    'Шубы и дубленки': 'Fur coats and sheepskin coats',
    'Платья-рубашки': 'Shirt dresses',
    'Водолазки': 'Turtlenecks',
    'Ночные рубашки': 'Nightgowns',
    'Платья-футболки': 'T-shirt dresses',
    'Укороченные': 'Cropped',
    'Пончо': 'Ponchos',
    'Кроп-топы': 'Crop tops',
    'Оверсайз': 'Oversized',
    'Пижамы': 'Pajamas',
    'Носки': 'Socks',
    'Бюстгальтеры': 'Bras',
    'Шорты': 'Shorts',
    'Трусы': 'Underwear',
    'Брифы': 'Briefs',
    'Боксеры': 'Boxers',
    'Трусы-шорты': 'Boxer briefs',
    'Дождевики': 'Raincoats',
    'Футболки': 'T-shirts',
    'Верхняя одежда': 'Outerwear',
    'Рашгарды': 'Rash guards',
    'Корректирующее белье': 'Shapewear',
    'Комбинезоны': 'Overalls',
    'Домашняя одежда': 'Homewear',
    'В клетку': 'Plaid',
    'Леггинсы и джеггинсы': 'Leggings and jeggings',
    'Джемперы, свитеры и кардиганы': 'Jumpers, sweaters, and cardigans',
    'Спортивная одежда': 'Sportswear',
    'Джинсовые': 'Denim',
    'Платья и туники': 'Dresses and tunics',
    'Толстовки и худи': 'Hoodies and sweatshirts',
    'Юбки': 'Skirts',
    'Платья и сарафаны': 'Dresses and sundresses',
    'Комплекты': 'Sets',
    'Пляжная одежда': 'Beachwear',
    'Футболки, майки, топы': 'T-shirts, tank tops, tops',
    'С открытыми плечами': 'Off-shoulder',
    'Блузы и рубашки': 'Blouses and shirts',
    'Джинсы': 'Jeans',
    'Пиджаки, жилеты и костюмы': 'Blazers, vests, and suits',
    'Боди': 'Bodysuits',
    'Корсеты': 'Corsets',
    'Боди и песочники': 'Bodysuits and rompers',
    'Костюмы и жилеты': 'Suits and vests',
    'Джемперы и кардиганы': 'Jumpers and cardigans',
    'Носки и колготки': 'Socks and tights',
    'Нижнее белье': 'Underwear',
    'Ползунки и штанишки': 'Creepers and pants',
    'Толстовки и свитшоты': 'Hoodies and sweatshirts',
    'Водолазки и лонгсливы': 'Turtlenecks and long sleeves',
    'Футболки и поло': 'T-shirts and polos',
    'Кружевные': 'Lace',
    'Платья-комбинации': 'Slip dresses',
    'Купальники': 'Swimsuits',
    'В рубчик': 'Ribbed',
    'Вязаные': 'Knitted',
    'Майки': 'Tank tops',
    'Топы': 'Tops',
    'На бретельках': 'With straps',
    'С коротким рукавом': 'Short-sleeved',
    'Пляжные': 'Beachwear',
    'Шифоновые': 'Chiffon',
    'Платья-футляры': 'Sheath dresses',
    'Спортивные': 'Sports',
    'Свадебные': 'Wedding',
    'С принтом': 'Printed',
    'Кожаные': 'Leather',
    'Комплекты белья': 'Lingerie sets',
    'С длинным рукавом': 'Long-sleeved',
    'На запах': 'Wrap-around',
    'Повседневные': 'Casual',
    'Колготки': 'Tights',
    'Хлопковые': 'Cotton',
    'Вечерние': 'Evening',
    'Льняные': 'Linen',
    'Туники и накидки': 'Tunics and cover-ups',
    'Плавки': 'Swim briefs',
    'Шорты для плавания': 'Swim shorts',
    'Полусапоги': 'Ankle boots',
    'Косынки': 'Scarves',
    'Шапки': 'Hats',
    'Бейсболки': 'Baseball caps',
    'Панамы': 'Bucket hats',
    'Шляпы': 'Hats',
    'Карнавальные костюмы': 'Costumes',
    'Головные уборы': 'Headwear',
    'Термобелье': 'Thermal underwear',
    'Рубашки-поло': 'Polo shirts',
    'Для рук и лица': 'For hands and face',
    'В полоску': 'Striped',
    'Нагрудники': 'Bibs',
    'Шелковые': 'Silk',
    'Одежда': 'Clothing',
    'Форма': 'Uniform',
    'Бриджи': 'Capri pants',
    'Носки и гетры': 'Socks and leggings',
    'Тайтсы': 'Tights',
    'Полотенца-халаты': 'Towel robes',
    'Поло': 'Polos',
    'Аксессуары': 'Accessories',
    'Система ГРМ и ременной привод': 'Timing system and belt drive',
    'Кроссовки': 'Sneakers',
    'Серфинг': 'Surfing',
    'С длинными рукавами': 'Long-sleeved'
}
