# Updated dictionaries with English keys and Russian values
category_1 = {
    'Clothing, shoes': 'Одежда, обувь',
    'Clothing': 'Одежда',
    'Fast delivery products': 'Товары с быстрой доставкой',
    'Home goods': 'Товары для дома',
    'Sports and leisure': 'Спорт и отдых',
    'Electronics': 'Электроника',
    'ReCommerce products': 'Товары ReCommerce'
}

category_2 = {
    'Men\'s shoes': 'Мужская обувь',
    'Women\'s shoes': 'Женская обувь',
    'Men\'s clothing': 'Мужская одежда',
    'Women\'s clothing': 'Женская одежда',
    'Children\'s clothing': 'Детская одежда',
    'Children\'s accessories': 'Детские аксессуары',
    'Women\'s accessories': 'Женские аксессуары',
    'Men\'s accessories': 'Мужские аксессуары',
    'Hair care': 'Уход за волосами',
    'Home textiles': 'Текстиль для дома',
    'Toys': 'Игрушки',
    'Winter sports': 'Зимние виды спорта',
    'Hiking and outdoor activities': 'Походы и активный отдых',
    'Wheel sports': 'Колесный спорт',
    'Bedding': 'Постельное белье',
    'None': 'nan',  
    'Hunting and fishing': 'Охота и рыбалка',
    'Fitness and gym': 'Фитнес и спортзал',
    'Team sports': 'Командные виды спорта',
    'Smartwatches and bracelets': 'Умные часы и браслеты',
    'Running and walking': 'Бег и ходьба',
    'Tennis and badminton': 'Теннис и бадминтон',
    'Water sports': 'Водные виды спорта',
    'Spare parts': 'Запчасти',
    'Yoga': 'Йога'
}

category_3 = {
    'Sneakers': 'Кроссовки',
    'Outerwear': 'Верхняя одежда',
    'Canvas shoes': 'Кеды',
    'Sneakers, canvas shoes, cleats': 'Кроссовки, кеды, бутсы',
    'Hoodies and sweatshirts': 'Толстовки и свитшоты',
    'Slip-ons': 'Слипоны',
    'Homewear': 'Домашняя одежда',
    'T-shirts': 'Футболки',
    'Sportswear': 'Одежда для спорта',
    'Jumpers, sweaters, and cardigans': 'Джемперы, свитеры и кардиганы',
    'Trousers': 'Брюки',
    'Blouses and shirts': 'Блузы и рубашки',
    'Dresses and sundresses': 'Платья и сарафаны',
    'Hoodies, sweatshirts, and sweaters': 'Худи, толстовки, свитшоты',
    'Jeans': 'Джинсы',
    'Shirts': 'Рубашки',
    'Blazers, jackets, and vests': 'Пиджаки, жакеты и жилеты',
    'Blazers, vests, and suits': 'Пиджаки, жилеты и костюмы',
    'Shorts': 'Шорты',
    'T-shirts and polos': 'Футболки и поло',
    'Skirts': 'Юбки',
    'Thermal underwear': 'Термобелье',
    'Long sleeves': 'Лонгсливы',
    'Leggings': 'Леггинсы',
    'Tops and tank tops': 'Топы и майки',
    'Socks and tights': 'Носки и колготки',
    'Underwear': 'Нижнее белье',
    'Overalls': 'Комбинезоны',
    'Socks': 'Носки',
    'For girls': 'Для девочек',
    'For boys': 'Для мальчиков',
    'None': 'nan',
    'For newborns': 'Для новорожденных',
    'Beachwear': 'Пляжная одежда',
    'Bodysuits': 'Боди',
    'Tank tops': 'Майки',
    'Boots and ankle boots': 'Сапоги и полусапожки',
    'Headwear': 'Головные уборы',
    'Suits and sets': 'Костюмы и комплекты',
    'Accessories for girls': 'Аксессуары для девочек',
    'Accessories for boys': 'Аксессуары для мальчиков',
    'Hair styling products': 'Средства для укладки волос',
    'Towels': 'Полотенца',
    'Toys for toddlers': 'Игрушки для малышей',
    'Newborn accessories': 'Аксессуары для новорожденных',
    'Hair accessories': 'Аксессуары для волос',
    'Belts': 'Ремни',
    'Trekking': 'Треккинг',
    'Clothing': 'Одежда',
    'Skiing': 'Лыжный спорт',
    'Backpacks': 'Рюкзаки',
    'Costumes': 'Карнавальные костюмы',
    'Sailing': 'Парусный спорт',
    'Football': 'Футбол',
    'Cycling': 'Велоспорт',
    'Swimming': 'Плавание',
    'Sandals': 'Сандалии',
    'Tennis': 'Большой теннис',
    'Wallets': 'Кошельки',
    'Boys\' shoes': 'Обувь для мальчиков',
    'Capri pants and shorts': 'Бриджи и капри',
    'Surfing and wakeboarding': 'Серфинг и вейкбординг',
    'Smartwatches': 'Умные часы'
}

category_4 = {
    'Hoodies': 'Толстовки',
    'Jackets': 'Куртки',
    'Down jackets': 'Пуховики',
    'Robes': 'Халаты',
    'Vests': 'Жилеты',
    'Suits': 'Костюмы',
    'Coats': 'Пальто',
    'Trousers': 'Брюки',
    'Parkas': 'Парки',
    'Leggings': 'Леггинсы',
    'Raincoats and trench coats': 'Плащи и тренчи',
    'Jumpers': 'Джемперы',
    'Blouses': 'Блузы',
    'Shirts': 'Рубашки',
    'Dresses': 'Платья',
    'Sweatshirts': 'Свитшоты',
    'Sweaters': 'Свитеры',
    'Blazers': 'Пиджаки',
    'Jackets': 'Жакеты',
    'Sundresses': 'Сарафаны',
    'Hoodies': 'Худи',
    'Cardigans': 'Кардиганы',
    'Fur coats and sheepskin coats': 'Шубы и дубленки',
    'Shirt dresses': 'Платья-рубашки',
    'Turtlenecks': 'Водолазки',
    'Nightgowns': 'Ночные рубашки',
    'T-shirt dresses': 'Платья-футболки',
    'Cropped': 'Укороченные',
    'Ponchos': 'Пончо',
    'Crop tops': 'Кроп-топы',
    'Oversized': 'Оверсайз',
    'Pajamas': 'Пижамы',
    'Socks': 'Носки',
    'Bras': 'Бюстгальтеры',
    'Shorts': 'Шорты',
    'Underwear': 'Трусы',
    'Briefs': 'Брифы',
    'Boxers': 'Боксеры',
    'Boxer briefs': 'Трусы-шорты',
    'Raincoats': 'Дождевики',
    'T-shirts': 'Футболки',
    'Outerwear': 'Верхняя одежда',
    'Rash guards': 'Рашгарды',
    'Shapewear': 'Корректирующее белье',
    'Overalls': 'Комбинезоны',
    'Homewear': 'Домашняя одежда',
    'Plaid': 'В клетку',
    'Leggings and jeggings': 'Леггинсы и джеггинсы',
    'Jumpers, sweaters, and cardigans': 'Джемперы, свитеры и кардиганы',
    'Sportswear': 'Спортивная одежда',
    'Denim': 'Джинсовые',
    'Dresses and tunics': 'Платья и туники',
    'Hoodies and sweatshirts': 'Толстовки и худи',
    'Skirts': 'Юбки',
    'Dresses and sundresses': 'Платья и сарафаны',
    'Sets': 'Комплекты',
    'Beachwear': 'Пляжная одежда',
    'T-shirts, tank tops, tops': 'Футболки, майки, топы',
    'Off-shoulder': 'С открытыми плечами',
    'Blouses and shirts': 'Блузы и рубашки',
    'Jeans': 'Джинсы',
    'Blazers, vests, and suits': 'Пиджаки, жилеты и костюмы',
    'Bodysuits': 'Боди',
    'Corsets': 'Корсеты',
    'Bodysuits and rompers': 'Боди и песочники',
    'Suits and vests': 'Костюмы и жилеты',
    'Jumpers and cardigans': 'Джемперы и кардиганы',
    'Socks and tights': 'Носки и колготки',
    'Underwear': 'Нижнее белье',
    'Creepers and pants': 'Ползунки и штанишки',
    'Hoodies and sweatshirts': 'Толстовки и свитшоты',
    'Turtlenecks and long sleeves': 'Водолазки и лонгсливы',
    'T-shirts and polos': 'Футболки и поло',
    'Lace': 'Кружевные',
    'Slip dresses': 'Платья-комбинации',
    'Swimsuits': 'Купальники',
    'Ribbed': 'В рубчик',
    'Knitted': 'Вязаные',
    'Tank tops': 'Майки',
    'Tops': 'Топы',
    'With straps': 'На бретельках',
    'Short-sleeved': 'С коротким рукавом',
    'Beachwear': 'Пляжные',
    'Chiffon': 'Шифоновые',
    'Sheath dresses': 'Платья-футляры',
    'Sports': 'Спортивные',
    'Wedding': 'Свадебные',
    'Printed': 'С принтом',
    'Leather': 'Кожаные',
    'Lingerie sets': 'Комплекты белья',
    'Long-sleeved': 'С длинным рукавом',
    'Wrap-around': 'На запах',
    'Casual': 'Повседневные',
    'Tights': 'Колготки',
    'Cotton': 'Хлопковые',
    'Evening': 'Вечерние',
    'Linen': 'Льняные',
    'Tunics and cover-ups': 'Туники и накидки',
    'Swim briefs': 'Плавки',
    'Swim shorts': 'Шорты для плавания',
    'Ankle boots': 'Полусапоги',
    'Scarves': 'Косынки',
    'Hats': 'Шапки',
    'Baseball caps': 'Бейсболки',
    'Bucket hats': 'Панамы',
    'Hats': 'Шляпы',
    'Costumes': 'Карнавальные костюмы',
    'Headwear': 'Головные уборы',
    'Thermal underwear': 'Термобелье',
    'Polo shirts': 'Рубашки-поло',
    'For hands and face': 'Для рук и лица',
    'Striped': 'В полоску',
    'Bibs': 'Нагрудники',
    'Silk': 'Шелковые',
    'Clothing': 'Одежда',
    'Uniform': 'Форма',
    'Capri pants': 'Бриджи',
    'Socks and leggings': 'Носки и гетры',
    'Tights': 'Тайтсы',
    'Towel robes': 'Полотенца-халаты',
    'Polos': 'Поло',
    'Accessories': 'Аксессуары',
    'Timing system and belt drive': 'Система ГРМ и ременной привод',
    'Sneakers': 'Кроссовки',
    'Surfing': 'Серфинг',
    'Long-sleeved': 'С длинными рукавами'
}
